# Generated by Django 5.2 on 2026-04-13 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('contrato_assinado', models.BooleanField(default=False, verbose_name='Contrato Assinado?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='PlanoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o valor padrão do plano.', max_digits=10, null=True, verbose_name='Valor Cobrado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_contratados', to='crm.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clientes_vinculados', to='crm.plano')),
            ],
            options={
                'verbose_name': 'Plano do Cliente',
                'verbose_name_plural': 'Planos dos Clientes',
                'unique_together': {('cliente', 'plano')},
            },
        ),
    ]
