# Generated by Django 6.0.4 on 2026-04-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='planocliente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('pausado', 'Pausado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='plano',
            name='servico',
            field=models.ManyToManyField(choices=[('ZAP', 'ZAPFLOW'), ('CONS', 'CONSULTORIA'), ('DEV', 'DESENVOLVIMENTO'), ('LP', 'LANDING PAGE')], default='ZAP', to='crm.servico'),
        ),
    ]
