# Generated by Django 6.0.4 on 2026-04-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_cliente_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='servico',
            field=models.ManyToManyField(default='ZAP', to='crm.servico'),
        ),
    ]
