# Generated by Django 6.0.4 on 2026-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_plano_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Plano'),
        ),
    ]
