# Generated by Django 6.0.4 on 2026-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_plano_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocliente',
            name='data_vencimento',
            field=models.DateField(default='2026-04-10', verbose_name='Data de Vencimento'),
        ),
    ]
