# Generated by Django 6.0.4 on 2026-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_planocliente_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocliente',
            name='data_vencimento',
            field=models.DateField(default='2026-04-10', verbose_name='Data de Vencimento'),
        ),
    ]
