# Generated by Django 6.0.4 on 2026-04-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_planocliente_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planocliente',
            name='data_vencimento',
        ),
    ]
