# Generated by Django 6.0.4 on 2026-04-17 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_planocliente_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocliente',
            name='data_vencimento',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Data de Vencimento'),
        ),
    ]
